#!/bin/sh
# Generate ~/Applications/RackFork.app — a thin Dock-able wrapper.
#
# WHY: the build produces a bare command-line executable, not a Mac app bundle.
# The log line "Bundle path:" comes out empty, macOS gives it no app identity, and
# it is awkward to find in the Dock or via Cmd-Tab. That is a real obstacle when
# working with screen magnification, not a cosmetic one.
#
# This wrapper does NOT copy Rack anywhere. It runs the binary in place, so a
# rebuild takes effect immediately with no reinstall step. It also does not
# involve `make dist`, so nothing under res/ is copied into a bundle.
#
# HOW IT WORKS: the bundle's executable is a script that `exec`s run-library.sh,
# which in turn `exec`s ./Rack. Because exec preserves the process ID, macOS keeps
# associating that PID with this bundle, so the Rack window belongs to RackFork.app
# and gets a proper Dock tile and Cmd-Tab entry.
#
# THE CATCH, and why RACK_SYSTEM_DIR is set below: in normal mode Rack finds its
# system directory through the Core Foundation main bundle. Once it is running
# inside a bundle, that resolves to the bundle's own Resources folder, which does
# not contain res/, Core.json or cacert.pem — Rack would fail to find its assets.
# src/asset.cpp checks the RACK_SYSTEM_DIR environment variable BEFORE the macOS
# bundle branch, so setting it here keeps the system directory pointed at the repo.
#
# Rerun this script after moving the repo. Deliberately no icon: using VCV's
# icon.icns would brand a personal fork as the official product, which is a
# trademark question separate from the panel licence.

set -e

REPO=$(cd "$(dirname "$0")" && pwd -P)
APP="$HOME/Applications/RackFork.app"

case "$REPO" in
	*" "*)
		echo "Repo path contains a space: $REPO" >&2
		echo "Rack's build system does not tolerate that. Move it first." >&2
		exit 1
		;;
esac

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS"
mkdir -p "$APP/Contents/Resources"

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleName</key>
	<string>RackFork</string>
	<key>CFBundleDisplayName</key>
	<string>RackFork</string>
	<key>CFBundleIdentifier</key>
	<string>com.chrisgr.rackfork</string>
	<key>CFBundleExecutable</key>
	<string>RackFork</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleVersion</key>
	<string>2.6.6</string>
	<key>CFBundleShortVersionString</key>
	<string>2.6.6</string>
	<key>NSHighResolutionCapable</key>
	<true/>
	<key>LSApplicationCategoryType</key>
	<string>public.app-category.music</string>
</dict>
</plist>
PLIST

cat > "$APP/Contents/MacOS/RackFork" <<LAUNCHER
#!/bin/sh
# Generated by make-app.sh — edit that script, not this file.
export RACK_SYSTEM_DIR="$REPO"
exec "$REPO/run-library.sh"
LAUNCHER

chmod +x "$APP/Contents/MacOS/RackFork"

# Ad-hoc code signature. Not about security — it gives the bundle a stable identity for
# macOS privacy permissions. The user folder lives in ~/Documents, which is TCC
# protected, so the first launch raises a system consent prompt. An unsigned bundle has a
# weaker identity, and the granted permission is more likely to be forgotten. Harmless if
# codesign is unavailable.
codesign --force --sign - "$APP" 2>/dev/null || echo "note: could not ad-hoc sign (harmless)"

# Make Finder and the Dock notice the new bundle rather than a cached version.
touch "$APP"
plutil -lint "$APP/Contents/Info.plist"

echo "Created $APP"
echo "Pointing at repo: $REPO"
